# Generated by Django 4.2.3 on 2023-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=300, verbose_name='آدرس الکترونیکی')),
                ('number', models.IntegerField(default=1, verbose_name='تعداد')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
