# Generated by Django 4.2.3 on 2023-07-24 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0002_food_type_food_alter_food_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('number', models.IntegerField(default=1, verbose_name='تعداد')),
                ('food', models.ManyToManyField(related_name='sabad', to='foods.food', verbose_name='غذاها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabad', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
