# Generated by Django 4.2.3 on 2023-07-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_sabad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='food',
        ),
        migrations.RemoveField(
            model_name='sabad',
            name='user',
        ),
    ]
