# Generated by Django 4.2.3 on 2023-07-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0004_remove_sabad_food_remove_sabad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabad', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
