# Generated by Django 4.2.3 on 2023-07-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_sabad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabad', to='foods.food', verbose_name='غذاها'),
        ),
    ]
