# Generated by Django 4.2.3 on 2023-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_sabad_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
