# Generated by Django 4.2.3 on 2023-07-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_sabad_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='Is_final',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده یا نشده'),
        ),
    ]
