# Generated by Django 4.2.3 on 2023-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_sabad_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='order_number',
            field=models.BigIntegerField(default=-1, verbose_name='شماره سفارش'),
        ),
    ]
