# Generated by Django 4.2.3 on 2023-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_sabad_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabad',
            name='order_number',
            field=models.CharField(default='-1', max_length=800, verbose_name='شماره سفارش'),
        ),
    ]
